export PATH=/usr/local/cuda-8.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
python SteerNet.py
#python SteerNetL1.py
#python SteerNetL2.py
#python SteerNetL12.py
#python SteerNetSGD.py
#python SteerNetL2SGD.py
