#!/bin/bash
echo "DATA COLLECTION"
echo "Clearing files..."
cd ~/Formula1Epoch/datacollection/data/camera
echo "Clearing count.txt..."
echo "done."
echo "Clearing timestamp.txt..."
> timestamp.txt
echo "done."
echo "Clearing images..."
cd /media/ubuntu/A802-B19C
rm images/*
echo "done."
echo "Clearing joydata.txt..."
> ~/Formula1Epoch/datacollection/data/joydata.txt
echo "done."
echo "Cleared files."
echo "Starting collection..."
echo "Starting racecar..."
cd ~/racecar-ws
xterm -e "source devel/setup.bash && roslaunch racecar teleop.launch" &
sleep 10
echo "done."
cd
echo "Starting joystick collection..."
xterm -e "rostopic echo /vesc/joy > ~/Formula1Epoch/datacollection/data/joydata.txt" &
echo "done."
echo "Starting camera collection..."
cd ~/Formula1Epoch/datacollection/data/camera
gcc -o test ~/Formula1Epoch/datacollection/data/camera/main.c
sleep 10
./test &
echo "ALL COLLECTION STARTED" &
wait

